import Head from "next/head";
//import Image from "next/image";
import Content from "./content";
import Social from "./social";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Journey</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My Journey as a Computer Science Undergraduate
        </h1>
        <p>By: Zdravko Bozhkov</p>
      </main>

      <div>
        <Content />
      </div>

      <footer className={styles.footer}>
        <Social />
      </footer>
    </div>
  );
}
